[2025-04-29T19:12:38.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T19:12:38.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:12:36.720425+00:00 [queued]>
[2025-04-29T19:12:38.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:12:36.720425+00:00 [queued]>
[2025-04-29T19:12:38.708+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-29T19:12:38.732+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_pst> on 2025-04-29 19:12:36.720425+00:00
[2025-04-29T19:12:38.740+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=744) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T19:12:38.743+0000] {standard_task_runner.py:63} INFO - Started process 745 to run task
[2025-04-29T19:12:38.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pstspark', 'run_spark_pst', 'manual__2025-04-29T19:12:36.720425+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/pstspark.py', '--cfg-path', '/tmp/tmpv8l4rwlh']
[2025-04-29T19:12:38.746+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask run_spark_pst
[2025-04-29T19:12:38.827+0000] {task_command.py:426} INFO - Running <TaskInstance: pstspark.run_spark_pst manual__2025-04-29T19:12:36.720425+00:00 [running]> on host 3d59bb7e8591
[2025-04-29T19:12:39.028+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pstspark' AIRFLOW_CTX_TASK_ID='run_spark_pst' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T19:12:36.720425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T19:12:36.720425+00:00'
[2025-04-29T19:12:39.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T19:12:39.064+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T19:12:39.065+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pstspark.py", line 35, in RunSparkPst
    df = spark.read.format("jdbc").options(url=url, table="employees", properties=properties)
         ^^^^^^^^^^
AttributeError: 'Builder' object has no attribute 'read'
[2025-04-29T19:12:39.108+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pstspark, task_id=run_spark_pst, run_id=manual__2025-04-29T19:12:36.720425+00:00, execution_date=20250429T191236, start_date=20250429T191238, end_date=20250429T191239
[2025-04-29T19:12:39.160+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task run_spark_pst ('Builder' object has no attribute 'read'; 745)
[2025-04-29T19:12:39.201+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-29T19:12:39.285+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T19:12:39.307+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
